grove:
  intent: >-
    Structured persistence framework for object storage,
    bringing snapshots, metadata, and safe write semantics
    without running a database.
  horizon: "generational"
  role: "library"
  phase: "consolidating"
  steward: "Andrew"
  consolidation_interval_days: 90
