version: "3"

tasks:
  format:
    desc: Format and auto-fix code
    aliases: [fmt]
    cmds:
      - golangci-lint run --fix ./...

  lint:
    desc: Run linters (no fixes)
    cmds:
      - golangci-lint run ./...
      - yamllint -s .

  test:
    desc: Run tests
    cmds:
      - go test ./...

  test:race:
    desc: Run tests with race detector
    cmds:
      - go test -race -count=1 ./...

  build:
    desc: Build all packages
    cmds:
      - go build ./...

  examples:
    desc: Build and run examples
    cmds:
      - go run ./examples/default_layout
      - go run ./examples/hive_layout
      - go run ./examples/blob_upload
      - go run ./examples/manifest_driven
      - go run ./examples/stream_write_records
      - go run ./examples/parquet

  snippets:
    desc: Verify runnable markdown snippets
    cmds:
      - ./scripts/verify-snippets.sh

  s3:up:
    desc: Start S3-compatible test services (LocalStack + MinIO)
    cmds:
      - docker compose -f lode/s3/docker-compose.yaml up -d

  s3:down:
    desc: Stop S3-compatible test services
    cmds:
      - docker compose -f lode/s3/docker-compose.yaml down

  integration:
    desc: Run integration tests (requires s3:up first)
    cmds:
      - go test -v -count=1 ./lode/s3/... -integration

  bench:
    desc: Run all benchmarks (start s3:up first for S3 benchmarks)
    cmds:
      - go test -bench=. -benchmem -run=^$ ./lode/...
      - go test -bench=. -benchmem -run=^$ ./lode/s3/... -integration
