version: "3"

tasks:
  format:
    desc: Format and auto-fix code
    aliases: [fmt]
    cmds:
      - golangci-lint run --fix ./...

  lint:
    desc: Run linters (no fixes)
    cmds:
      - golangci-lint run ./...

  test:
    desc: Run tests
    cmds:
      - go test ./...

  test:race:
    desc: Run tests with race detector
    cmds:
      - go test -race -count=1 ./...

  build:
    desc: Build all packages
    cmds:
      - go build ./...

  examples:
    desc: Build and run examples
    cmds:
      - go run ./examples/default_layout
      - go run ./examples/hive_layout
      - go run ./examples/blob_upload
      - go run ./examples/manifest_driven
